### ISSUE TITLE
Setting date back causes new messages to appear at bottom of list.

### ISSUE THREAD

**Issue by comradekingu** [SilenceIM/Silence#466] opened 2016-10-18 11:00 UTC
Dropping ones phone and in turn having to re-seat the battery will reset the date.
When set to 01.01.00, notifications work as per usual, but new messages are then subjugated to the bottom of the list.

*Newer message
*Old message
→Newest message after resetting date

Upon opening Silence It would be better if SMSs were stacked in the order they arrived, with regard to the last received message.

→Newest message after resetting date
*Newer message
*Old message

Silence 0.14.3
Build ID: 3790d80 (from F-droid) on S2 (GT-I9100) replicant 4.2.2

**Comment by comradekingu** [comment] 2016-10-18 11:08
After setting the date back to normal, the messages received in the interim are still at the bottom.

**Comment by johanw666** [comment] 2016-10-20 22:44
Yes, they are sorted by the received date. If it irritates you the only way to solve it is to edit the date field in table sms in messages.db and restart Silence (force close it and start it). It's a unencrypted numerical field in standard Java datetime encoding.

**Comment by comradekingu** [comment] 2016-10-21 01:13
Right now it is not by sorted received date any more so than time goes backwards.
It is only the _perceived_ date, and wrongfully so in what  is the only case in which it doesn't adhere to latest at the top. The systems flawed perception and display of a timeline.
What I want is for it to actually be arranged in the order it is received.
Editing table data manually is a little bit on the unintuitive side, especially considering for there to be an annoyance, you need to know about it first. 

The interesting bit is finding your message where you would expect it to, not where it technically should be, based on fields that are also wrong. Today being to most people, where they would expect to find todays messages.
I don't think messages going missing, and potentially overlooked is a great way in tipping people off to their time being set erroneously. It is just the small set of unfortunate accidents leading up to the bigger disaster.

I learnt my lesson, and don't care as much about some messages being tagged erroneously. While I appreciate the effort, the workaround routes around the problem, and doesn't solve even that issue very well.

**Comment by doodhout** [comment] 2016-11-03 11:12
Or you could change the setting in SilenceIM that the received date of a message is the sent datetime of the text message rather than the system time at the point of receiving the message.

It can be found in Silence - Settings - SMS & MMS - Show sent time - switch to *enabled*.

**Comment by pR0Ps** [comment] 2017-07-02 19:00
@doodhout is correct, however that setting only adjusts the date displayed, not the date it sorts by. The reason we use the time of the phone to stamp messages is that it's the only thing we know for sure. Historically, the datetime supplied by the carrier is unreliable, especially when time zones come into play.

The time being wrong isn't as important when it's just being displayed next to the message since that's UI-only, but for the functionality of ordering messages, we always use the phone's time since it's the only thing we know for sure.

Unfortunately this causes issues when the phone's time is wrong. However, the phone's time being wrong enough to notice an issue tends to happen as a one-time-event and the cause is easier to understand, rather than messages always being ordered incorrectly because you forgot you enabled a setting.

**Closed by pR0Ps** 2017-07-02 19:00 UTC
