### ISSUE TITLE
[Feature Request] - SMS Scheduler

### ISSUE THREAD

**Issue by darryl-grennan** [SilenceIM/Silence#421] opened 2016-06-16 21:33 UTC
Hi folks!

I just wanted to make the suggestion that it would be really handy to have the functionality of "SMS Scheduler".  It causes the messenger to delay/set (on-device) when you prepared message is to be sent.  Allows for recurrences as well.

**Comment by ClubWDW** [comment] 2016-06-16 23:54
+1

**Comment by pR0Ps** [comment] 2016-06-17 16:02
Closing as dupe of #314

**Closed by pR0Ps** 2016-06-17 16:02 UTC
