### ISSUE TITLE
Multi recipients

### ISSUE THREAD

**Issue by xavihernandez** [SilenceIM/Silence#259] opened 2015-10-06 10:18 UTC
Hi,

For the moment, messages for several recipients are handled via MMS and conversation group (even if I choose "Broadcast" - "Diffusion" in French - in group screen). I think you should let the user choose if he wants a Conversation (via MMS) or just send the same messages to severeal recipient (via SMS). I think the 2 choice "Conversation" and "Broadcast" in group screen is for that, but it does not change anything.

**Comment by franciskittu** [comment] 2015-10-10 05:55
+1 . I agree, it's a relevant missing feature.

**Comment by sevan6** [comment] 2015-11-25 16:08
+1
A friend asked me how to send group messages. I proudly showed him the two options but realized it was an MMS "broadcast" (sent only to one recipient) in both cases…   ^^'

**Comment by jpierre03** [comment] 2015-12-01 15:53
+1

**Comment by blipp** [comment] 2016-01-17 13:25
+1

Some of my friends are accidentally sending MMS when they try to use the group message feature. Sure the text box mentions that SMSSecure will be sending a non-encrypted MMS, but I guess they don't pay attention to the message. Thus I would appreciate a way to configure the transport taken for group messages :) As mentioned in #151 MMS can be quite expensive in some countries/with some providers.

**Comment by doodhout** [comment] 2016-08-05 14:00
+1, this has just been a bother to me; I had to temporarily revert to my other SMS app (that I stopped using after discovering Silence) to be able to send a SMS message to multiple recipients directly.

**Comment by zoff99** [comment] 2016-08-05 14:03
please also add an option to totally disable any MMS usage (send or receive).
here in europe SMS are mostly free, but MMS are very very silly expensive.

i like to make sure that i never ever under any circumstance send or download MMS

**Comment by Kyoshiro-san** [comment] 2016-09-27 18:36
Right now, sending to multiple contacts is only possible by creating a group (not very intuitive for a quick announce), thus sending a MMS discussion including the recipient list to all members, which might cause privacy issues.

A friend of mine I showed the app to used this to send his new phone number to all his contacts, they all got his whole address book in the headers... This is quite embarrassing when we're talking about privacy ^^'

Is there a way to have proper "send SMS to multiple contacts" feature ?
Also see #130 seems like a duplicate of this feature request (or the reverse)
Upstream discussion : https://github.com/WhisperSystems/Signal-Android/issues/413
Cheers !

**Comment by pR0Ps** [comment] 2016-09-27 20:41
Correct, this is a duplicate, closing in favour of #130 (please direct additional comments there)

**Closed by pR0Ps** 2016-09-27 20:41 UTC
Labels: bug, enhancement
