### ISSUE TITLE
target API level 26 to still be able to push updates to PlayStore after November 1, 2018

### ISSUE THREAD

**Issue by tuxayo** [SilenceIM/Silence#717] opened 2018-09-17 12:07 UTC
https://developer.android.com/distribute/best-practices/develop/target-sdk
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

Current targetSdkVersion is 22 https://github.com/SilenceIM/Silence/blob/master/build.gradle#L146

**Comment by tuxayo** [comment] 2018-09-17 12:12
Great news, it's in progress.

https://github.com/SilenceIM/Silence/issues/703#issuecomment-419896412

> I’ve been able to contact @BLeQuerrec. He is very busy (and has no time to come here on GH), but still works on Silence when he gets some free time. His first priority currently is to upgrade the used Android API in order to meet the November 2018 API level 26 mandatory target deadline.

**Comment by williamdes** [comment] 2018-09-17 15:21
Duplicate of: #688 but still better than my issue :)

**Comment by tuxayo** [comment] 2018-09-17 15:48
Sorry I haven't found it when searching for dups ^^

**Comment by johanw666** [comment] 2018-10-21 09:41
After seeing what needed to be done in Signal I'm affraid it might be some more work. And Signal still suffers from bugs related to that transition in https://github.com/signalapp/Signal-Android/commit/87e6aa48bbdb7c088dffc53b7e26355be7b0483e like https://github.com/signalapp/Signal-Android/issues/8287 after https://github.com/signalapp/Signal-Android/commit/87e6aa48bbdb7c088dffc53b7e26355be7b0483e  and https://github.com/signalapp/Signal-Android/commit/89f97f57cb0f39c1852a975f0b8080216e990700 . I don't know if they are all relevalt for Silence but  I guess some are.

And then there are workarounds for bugs in Android like https://github.com/signalapp/Signal-Android/commit/45e0bb281faeb1fcd73b741a81aad08d5805baa0 and https://github.com/signalapp/Signal-Android/commit/feb9e1d513e3be8753d053b0524a54c0ab28f830

**Closed** 2019-08-03 23:04 UTC
