### ISSUE TITLE
storage of SMS backup

### ISSUE THREAD

**Issue by daniu-de** [SilenceIM/Silence#388] opened 2016-04-26 10:07 UTC
Hi,

If I understand correctly secure SMS does not use the Android system SMS storage which is why the system sms need to get imported. (reimporting the system sms database via Titanium did not import the latest sms but just the ones before I used sms secure ...)

This also means that changing from secure sms to another SMS app while keeping the old messages means that the sms somehow need to find their way back to the system storage. I guess that can be done with "SMS backup and restore" since secure sms claims that the non encrypted - text based backup format is compatible with this app.
However one thing I could not find out so far is: where does sms secure safe the backup?

I also think it is not so nice that sms secure seems to just backup the sms somewhere without telling where and most likely also without any kind of timestamp. I would appreciate to be able to have several versions of sms backups and of course I would like to be able to know where these backups are to put them in a safe place and also to delete them ...

best regards

**Comment by johanw666** [comment] 2016-04-26 18:18
It is saved in the root of the internal SD card, version 0.14.0 and later call the file `SilencePlaintextBackup.xml`.

**Comment by ArchangeGabriel** [comment] 2016-05-03 15:55
Note that this is the “SMS Backup & Restore” format file, and that it does not contains MMS. Currently, MMS can only be exported (and imported) with the full encrypted backup internal to Silence (in which case it’s a folder on the same place, called SilenceExport).

**Comment by crazy-max** [comment] 2016-05-10 20:49
Can you implement MMS backups in the plaintext backup ?

**Comment by ArchangeGabriel** [comment] 2016-05-23 22:55
@crazy-max There is already https://github.com/SilenceIM/Silence/issues/184 for this request.

**Comment by pR0Ps** [comment] 2016-10-05 23:23
Dupe of #184

**Closed by pR0Ps** 2016-10-05 23:23 UTC
