### ISSUE TITLE
Allow other apps to have access to unencrypted SMS messages

### ISSUE THREAD

**Issue by bodywithoutorgans** [SilenceIM/Silence#633] opened 2017-12-07 10:06 UTC
### Bug description
When Signal is set to receive all SMS messages, other applications cannot read standard unencrypted SMS messages.

### How to reproduce
- turn on "receive all SMS" option (not sure about the exact name of this option in English version)
- in Tasker set a profile with condition: event / received text and a task using eg. %SMSRB, %SMSRN variables (message body and sender name)

**Actual result:** 
- when an SMS arrives, the Tasker profile is not activated.
- when you run the Tasker task maually, it uses the last SMS that had been received before Silence was chosen as SMS client

**Expected result:** 
Apps like Tasker should have access to unencrypted SMS messages.

[The same issue in Signal](https://github.com/WhisperSystems/Signal-Android/issues/5491)

**Comment by johanw666** [comment] 2017-12-07 10:45
They have, but only when the message arrives. Android then gives a notification to all apps that have registered themselves as sms receivers. However, some apps don't work that way and poll the system sms database, which is not used when Silence is the default sms handler and stores the message in its own storage.

I would suggest to file a bug with Tasker about that. Alternative is to use Silence only for encrypted sms.

**Comment by pR0Ps** [comment] 2017-12-07 11:36
Duplicate of #145

**Closed** 2017-12-07 11:36 UTC
