### ISSUE TITLE
You can't start a secure conversation with yourself

### ISSUE THREAD

**Issue by tdelmas** [SilenceIM/Silence#622] opened 2017-10-26 14:22 UTC
### Bug description
You can't start a secure conversation with yourself

### How to reproduce
- Select  yourself to start a conversation
- Click on the lock  to start an encrypted conversation

**Actual result:** 

- The exchange key starts

**Expected result:** 

- The exchange key finishes

### Device info
- Device:  Samsung S4
- Android version: 5.0.1
- Silence version: 0.16.4

**Comment by ArchangeGabriel** [comment] 2017-10-27 16:16
On my side I can start a encrypted conversation, but keys were sent twice by both side (well, that’s me and me, but what I mean is that I have a total of 4 KEX messages) and then any message I send to myself is marked as “Wrongly encrypted message” (or whatever it is supposed to be in english) upon receiving it.

**Comment by BLeQuerrec** [comment] 2017-11-02 10:30
Silence doesn't support secure sessions with yourself because of the library it uses. If the SIM card discloses its phone number, Silence will check if the recipient's phone number is not the same as the SIM card one; if so, a toast is displayed and secure session starting is blocked; if not, encrypted messages result in incorrect encrypted ones as @ArchangeGabriel reported. This is an intended behaviour of the libsignal.

**Closed by BLeQuerrec** 2017-11-02 10:30 UTC
