### ISSUE TITLE
Evil Emoji Text Permacrashed Silence

### ISSUE THREAD

**Issue by cathalgarvey** [SilenceIM/Silence#458] opened 2016-09-28 20:28 UTC
Here's a very weird one for ye: I received an SMS from my sister last week that caused Silence to crash, and to then crash on opening until I wiped the data. I tried FCing the app, restarting the phone, everything; wiping the data was all that allowed me to continue using Silence.

Attached is a screenshot of the message from _her_ phone; by this point I had wiped my Silence data, so sadly I have nothing other than this to provide. Her phone is an Android; I can get more specific detail if it matters. Mine is an Alcatel Onetouch running Silence 0.14.3, Build ID 3790d80, installed from F-Droid.

Best guess: Something about the order of Emoji triggered a hook that expected an encrypted message, but my sister is too hostile to her own privacy to use Silence; this was all cleartext.

![evil_emoji](https://cloud.githubusercontent.com/assets/1167837/18931049/75e340ae-85c2-11e6-9033-30dd847b5bac.png)

**Comment by cathalgarvey** [comment] 2016-09-28 20:29
BTW, to be clear; it was the second sms full of emoji-vomit that killed my Silence, not the solitary emoji heart. :)

**Comment by cathalgarvey** [comment] 2016-09-28 20:33
Hmm, possibly related: #384 - Silence using a custom Emoji package, is that package safe when it receives unknown emoji?

**Comment by johanw666** [comment] 2016-09-29 01:58
Since Silence now has a full backup option, you could try to repeat it:

1. Make encrypted backup
2. Ask het to resend this sms
3. Crash - use logcat or something like that (if you're rooted or use an old Android version), otherwise I don't know.
4 Send log.
5. Restore beckup

Alternative, if you can't get the logs:

1.  Make encrypted backupand AND STORE IT SOMEWHERE SAFE!
2. Wipe data and restart.
3. Ask het to resend this sms - crash
4. Make encrypted backup. Since this will overwrite the previous backup the previous backup has to be saved somewhere safe!
5. Store new backup somewhere and post it online so someone with root access can recreate the logs. Because (2) will also create a new key so your real identity key wil never be posted.
6. Restore old backup from (1).

**Comment by BastienLQ** [comment] 2016-11-13 11:19
Can't reproduce. Might be fixed by b3c53b569b5066afa2c8288070ca879098814cce. Leaving open until you can confirm it.

**Comment by BastienLQ** [comment] 2017-01-07 23:58
@cathalgarvey Can you reproduce this bug with the latest published version of Silence?

**Closed** 2018-03-07 12:30 UTC
Labels: bug, waiting for information
