### ISSUE TITLE
Verry long SMS decryption error

### ISSUE THREAD

**Issue by nyradr** [SilenceIM/Silence#519] opened 2017-01-10 21:17 UTC
### Bug description

The app is unable to decrypt text message up to 15 SMS (~1540 characters) long.
Sending a message made of 14 SMS works but up to 15 SMS the app can't rebuild the original message.

### How to reproduce
- generate long text (15 SMS) long  (we take a 1550 characters text to reach 15 sms)
- send message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The target receive 15 sms full of gibberish (the encrypted text)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Probably the sent message.

### Device info
- Device: Android 6.0.1 for me, Android 2.3.6 for my contact
- Silence version and build ID: fd8f2a2 for me

### Link to debug log

https://gist.github.com/anonymous/db9f8f1b1d66b37596c54dbfb1f8a680

**Comment by BastienLQ** [comment] 2017-01-10 21:21
Duplicate of #288.

**Closed by BastienLQ** 2017-01-10 21:21 UTC
