### ISSUE TITLE
Notification repeat after unlocking with passphrase

### ISSUE THREAD

**Issue by ravas-lt** [SilenceIM/Silence#496] opened 2016-12-14 13:34 UTC
### How to reproduce
- update to the laatest version
- Lock Silence with passphrase
- receive sms
- unlock silence with passphrase

**Actual result:** after unlocking silence with passphrase, the tone and vibration notification repeat for the unread messages (sometimes multiple times)
**Expected result:** after unlocking silence with passphrase there are no repeated notifications.

### Device info
- Device: Oneplus One
- Android version: 6.0.1
- Silence version and build ID: version 0.14.6, Build ID: fd8f2a2

**Comment by ArchangeGabriel** [comment] 2016-12-14 13:36
See #488 and #490 to tell whether you have the same issue.

**Comment by ravas-lt** [comment] 2016-12-14 13:39
sorry, i'm new, just noticet those posts, and yes it's pretty much the same, only for me, the notifications repeat as many times as there are unread sms (encrypted or not)

**Comment by pR0Ps** [comment] 2016-12-14 14:23
@ravas-It: thanks for the report! Closing this as a duplicate of #490

**Closed** 2016-12-14 14:24 UTC
