### ISSUE TITLE
Group-SMS turns automatically in MMS

### ISSUE THREAD

**Issue by DonCane** [SilenceIM/Silence#731] opened 2018-12-10 20:18 UTC
Hello,

I am a new member of this forum. I installed the silence app and I like it very much. But I have one problem: When I send a group-SMS then it turns automatically to a MMS. SMS is inclouded in the flat but I have to pay for a MMS. Is it possible to change the settings, that a group-SMS not turns in a MMS and send as a SMS to the group.

Thank you for your answer and help.

Greetings 
Alexander

**Comment by pR0Ps** [comment] 2018-12-10 20:50
Closing as duplicate of #130

**Closed by pR0Ps** 2018-12-10 20:50 UTC
