### ISSUE TITLE
When automatic reception is deactivated, no "download" button in MMS message

### ISSUE THREAD

**Issue by sevan6** [SilenceIM/Silence#549] opened 2017-02-23 08:46 UTC
Conditions:
- automatic reception is deactivated for MMS
- encrypted conversation

Receive a MMS. 

Observed result:
A message indicating 'multimedia message'

Expected result:
A message indicating multimedia message, date and time and a button to download the MMS

When reactivating automatic reception, the MMS is received (looks like only the download button is missing)

Debug Log: https://gist.github.com/anonymous/e575c3c3741a5b954229aae3490c7f62

**Comment by ArchangeGabriel** [comment] 2017-02-23 09:52
Duplicate of #548 I think, which is fixed in master.

**Comment by BLeQuerrec** [comment] 2017-02-23 10:53
Duplicate of #548. v0.15.2 will fix that and is currently being compiled by F-Droid. It will be released soon.

**Closed by BLeQuerrec** 2017-02-23 10:53 UTC
