### ISSUE TITLE
Long SMS size limit unclear

### ISSUE THREAD

**Issue by Rox5** [SilenceIM/Silence#404] opened 2016-05-16 13:56 UTC
Hi,
The long SMS text attached below (for test purpose only) sent with Silence V 0.14.3 in **3G** mode will be correctly received, but only **partially stored** at sender side. 
Probably a text size limit somewhere which cuts the stored message.
SMS/MMS size limit is unclear (not specified in settings).

note: long SMS don't work properly in 4G mode with my operator, but this is an other issue.

_Moto G 2014 LTE - CyanogenMod 13 nightly - Silence V 0.14.3_
- [logcat.txt](https://github.com/SilenceIM/Silence/files/266236/logcat.txt) 
- [LongSMS_test.txt](https://github.com/SilenceIM/Silence/files/266279/LongSMS_test.txt)

**Comment by buzuck** [comment] 2016-05-25 22:22
This issue and #389 seem related to be related.

**Comment by pR0Ps** [comment] 2016-05-26 01:14
Closed as a dupe of #389

**Closed by pR0Ps** 2016-05-26 01:14 UTC
