### ISSUE TITLE
No implementatiin of SMS history into system dialer/protocols

### ISSUE THREAD

**Issue by malafred** [SilenceIM/Silence#532] opened 2017-02-09 18:50 UTC
Actually it's more a lacking feature tan a bug but pull requests seem unaccessible to me. 
Anyhow, unlike the stock messenger Silence does not integrate into the overall system protocol of all  calls and sms which that have been executed.
To me this is a crucial functiom as sometimes viewing the records helps me understand the timeline of contacts.

**Comment by pR0Ps** [comment] 2017-02-10 02:49
Duplicate of #145

**Closed by pR0Ps** 2017-02-10 02:49 UTC
