### ISSUE TITLE
Can't send SMSes to a group of users

### ISSUE THREAD

**Issue by axtux** [SilenceIM/Silence#413] opened 2016-06-03 03:19 UTC
I've created a group of 2 users, entered text, pushed "send" and the SMS got logged but I got the message "sent failed" (or similar, my phone is in french). If I go to details, I have a list of failed SMSes (here both failed) and if I try to send again (individually), the error occurs again. Not sure what I should do. I tried in both conversation and diffusion mode but both failed.

I made a debug report https://gist.github.com/anonymous/bd3c74d7863f85bd3e883979018da1f8

**Comment by axtux** [comment] 2016-06-07 22:06
Ok not sure why but now, I was able to send a group message in both conversation and diffusion mode. The application sent one MMS to each recipient (in both mode). I live in Belgium and here, SMSes are way cheaper than MMSes.

IMO, user should have the option to choose how to send group message. And one option should be to send one SMS to each recipient.

**Comment by BastienLQ** [comment] 2016-07-16 11:02
Duplicate of #130.

**Closed by BastienLQ** 2016-07-16 11:02 UTC
