### ISSUE TITLE
Long SMS are not send and/or received properly

### ISSUE THREAD

**Issue by buzuck** [SilenceIM/Silence#389] opened 2016-04-26 10:40 UTC
Hello,
This bug as been there for a while, I didn't take any time yet to report it.

Long messages containing 19 or more sms are not sent properly.
- From the sender point of view: the 19th sms and above are lost. Only the 18 firsts are sent.
- From the receiver point of view: the 18 are displayed separately, and are not deciphered.

Yes... Usually people are not sending their emails through text messages, but though... A very annoying bug for those who do ^^

Device's information:
- Moto G 1st gen (codename : falcon)
- Cyanogenmod v13.0
- Silence version : 0.14.1 (sender) - 0.13.0 (receiver)
- Debug logs (don't know if they will be of any use... : [silence.txt](https://github.com/SilenceIM/Silence/files/236391/silence.txt)  )

**Comment by lhark** [comment] 2016-06-09 18:52
Hi,
I think i've got a similar problem, but it manifests itself even for messages way shorter than 19 sms. I cannot be sure but it seems to fail to send if the message is larger than 1 SMS. I checked the last one that failed, it was 124 chars long, with special chars like "é" or "ç" (might change the encoding).

On the receiver side, whatever operator or messaging app they are using (so the messages aren't encrypted), they only recieve the first few dozen chars, and that's it.

Device information : 
* Xperia Ray
* Cyanogenmod 10
* Silence 0.14.3

**Comment by BastienLQ** [comment] 2016-07-16 11:00
Duplicate of #288.

**Closed by BastienLQ** 2016-07-16 11:00 UTC
